### ISSUE TITLE
Autocomplete does not work for nested files

### ISSUE THREAD

**Issue by 5Mixer** [snowkit/atom-haxe#48] opened 2015-11-07 07:21 UTC
While editing my pure haxe (no OpenFL, Haxeflixel, etc) autocomplete stops working while in files not in the folder that build.hxml is in.  Autocomplete works perfectly fine for all files in the same folder as build.hxml.

Screenshot of console:
https://i.gyazo.com/833078222224afbe9137fef03c09233a.png
See the line that says 'Display file was not found in class path'

Any ideas?

**Comment by 5Mixer** [comment] 2015-11-07 07:28
The --cwd is not putting it in the source file's folder, just the builds folder. Obviosly resetting the HXML file and everything isn't fixing the issue.

**Comment by jeremyfa** [comment] 2015-11-07 16:21
I cannot tell without knowing the contents of your hxml file and your directory structure, but I just tested and autocomplete works fine on any file that is in the class path, not only the directory of the hxml file. Of course the file still needs to be inside a directory referenced with `-cp some/directory`.

**Comment by 5Mixer** [comment] 2015-11-07 23:12
Ah, -cp was needed. I am however a little confused, I never had `-cp` in my hxml file before, and my project compiled it just fine. The `main.hx` file was in the same folder as `build.hxml`, and it accessed all the other files just fine.

I only have around 8 folders in my project (it is a medium sized project), and in order for autcomplete to work, I have to list every sub folder. Not a big deal, not at all, but it seems like it would be tedious for larger projects. Even if there was the option for `-cp Src/*` Anyhow, thanks for your help!

Screenshot of working build.hxml and file structure.
https://i.gyazo.com/7a3ec859f1ba3c3c60776ce77283cabd.png

Thank you for your help!

**Comment by jeremyfa** [comment] 2015-11-08 10:06
You should not need `-cp` for sub directories, as long as they are valid haxe packages. I am not sure it's a good idea to use subfolders with capital letters as well.

You can find more informations here: http://haxe.org/manual/type-system-modules-and-paths.html

Closing because it is not really an issue caused by atom-haxe.

**Closed as completed by jeremyfa** 2015-11-08 10:06 UTC
