### ISSUE TITLE
HaxeLinter.Linter is deprecated.

### ISSUE THREAD

**Issue by lewislepton** [snowkit/atom-haxe#34] opened 2015-07-20 16:10 UTC
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API

```
HaxeLinter.Linter (/Users/lepton/.atom/packages/linter/lib/linter.coffee:60:4)
new HaxeLinter (/Users/lepton/.atom/packages/haxe/lib/linting/linter.js:12:38)
Object.lint (/Users/lepton/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/lepton/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/lepton/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/lepton/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

**Comment by jeremyfa** [comment] 2015-07-20 22:09
Duplicate of #32

**Closed as completed by jeremyfa** 2015-07-20 22:09 UTC
